const Project = [
    {
        id: "1",
        title: "CRISP SALAD WORKS",
        slug: "CRISP SALAD WORKS",
        image: '/images/Projects/crisp.png',
        technology: "React, Node.js, TypeScript",
        preview_url: "https://crisp.co.jp/",
        short_description: `This is "CRISP SALAD WORKS," a custom salad specialty store. (A small exchange of hearts) We deliver salads filled with vegetables.`,
    },
    {
        id: "2",
        title: "COCONALA",
        slug: "COCONALA",
        image: '/images/Projects/coconala.png',
        technology: "React, Node.js, TypeScript",
        preview_url: "https://blog.coconala.co.jp/",
        short_description: `This is the account of Coconala, Inc., which operates Coconala, a skills marketplace where you can buy and sell knowledge, skills, and experience. We deliver "Coconala LIVE," which introduces the people of Coconala, and "My Skill Unlocking Diary," which tells the stories of users who have expanded their life possibilities with Coconala.`,
    },
    {
        id: "3",
        title: "Timee.co.jp",
        slug: "Timee.co.jp",
        image: '/images/Projects/timee.co.jp.png',
        technology: "React, Node.js, TypeScript",
        preview_url: "https://timee.co.jp/",
        short_description: `Timee is a part-time job recruitment service that matches the "hours you want to work" with the "hours you want to work."`,
    },
    {
        id: "4",
        title: "AI Mind Map Summarizer",
        slug: "AI Mind Map Summarizer",
        image: '/images/Projects/ai-mind-map.png',
        technology: "React, Node.js, TypeScript",
        preview_url: "https://mapify.so/",
        short_description: "Summarize YouTube, PDFs/Docs, URLs, Podcast and Meeting Recordings into Mind Maps in seconds. Powered by GPT, Gemini, or other top LLMs.",
    },
    {
        id: "5",
        title: "Gama Dent",
        slug: "Gama Dent",
        image: '/images/Projects/gama.png',
        technology: "React, Tailwind CSS, TypeScript",
        preview_url: "https://gama-dental.vercel.app",
        short_description: "Gama Dental offers features tailored to dental care or products, presented in an interactive manner due to its React-based development.",
    },
    {
        id: "6",
        title: "SWOM Swap Your Home",
        slug: "SWOM Swap Your Home",
        image: '/images/Projects/swom.png',
        technology: "TypeScript, Next.js, Tailwind CSS",
        preview_url: "https://swom.travel/en",
        short_description: "Swom is a members-only global travel community where you can exchange homes for free. Travel, work, or have fun without rent, hidden fees, or hassle. Make memories worldwide!",
    },
    {
        id: "7",
        title: "TriggerX",
        slug: "TriggerX",
        image: '/images/Projects/triggerX.png',
        technology: "Next.js, prismaORM, postgresql, Typescript, Tailwind, zustand, xyflow, React-hook-form",
        preview_url: "https://trigger-x-puce.vercel.app",
        short_description: "TriggerX is a workflow automation platform like Zapier, streamlining tasks, boosting productivity, and integrating essential tools.",
    },
    {
        id: "8",
        title: "CuteToInsane",
        slug: "CuteToInsane",
        image: '/images/Projects/cute.png',
        technology: "TypeScript, Next.js, Tailwind CSS",
        preview_url: "https://cutetoinsane.online",
        short_description: "CuteToInsane is a website specializing in blockchain NFT minting, focusing on mouse-themed NFTs for gaming. It features an exceptional UI and offers an amazing design, ensuring a seamless experience for minting and trading digital assets.",
    },
    {
        id: "9",
        title: "Maki Nishikino",
        slug: "Maki Nishikino",
        image: '/images/Projects/maki.png',
        technology: "React, Tailwind CSS, TypeScript",
        preview_url: "https://maki-me.vercel.app",
        short_description: "Promising a melodious and potentially rewarding investment journey",
    },
    {
        id: "10",
        title: "Kokomi Teruhashi",
        slug: "Kokomi Teruhashi",
        image: '/images/Projects/kokomi.png',
        technology: "React, SCSS",
        preview_url: "https://kokomi-me.vercel.app",
        short_description: "Promising a melodious and potentially rewarding investment journey",
    },
];

export default Project;